export const skills = [
  // languages & technologies
  "JavaScript",
  "TypeScript",
  "HTML",
  "CSS",
  "SCSS",
  // styles
  "Tailwind",
  "CSS Animations",
  "Responsive design",
  // frameworks
  "React",
  "SPA",
  "Next.js",
  "SSR",
  "ISR",
  "PPR",
  "React Native",
  "Vue",
  "Nuxt.js",
  "Angular",
  // state & data
  "React Context API",
  "MobX",
  "Redux",
  "Redux Toolkit",
  "React Query",
  "Rx.js",
  "Vuex",
  "NGRX",
  // api
  "REST API",
  "Axios",
  "GraphQL",
  "Apollo Client",
  "WebSocket",
  // forms & validation
  "React Hook Form",
  "Formik",
  "Zod",
  "Schema-driven forms",
  // UI & styling
  "Mantine",
  "Bootstrap",
  "Tailwind",
  "Styled Components",
  "shadcn/ui",
  "Framer Motion",
  // maps & visualization
  "VK Maps",
  "Yandex Maps",
  "Recharts",
  "Tiptap",
  // testing
  "Vitest",
  "Jest",
  "React Testing Library",
  // tools
  "Git",
  "Webpack",
  "Vite",
  "ESLint",
  "Prettier",
  "Figma",
  "Docker",
  "Storybook",
  // ci/cd
  "GitLab CI",
  "GitHub Actions",
  // mobile
  "Android",
  "Android SDK",
  "Kotlin",
  "Volley",
  "React Native",
  "React Navigation",
  "Reanimated",
  // web api
  "Canvas API",
  "Intersection Observer API",
  "Notifications API",
  "Service Workers",
  "PWA",
  // optimization
  "Pagination",
  "Infinite Scroll",
  "Lazy Loading",
  "Virtualization",
  // other libs
  "Three.JS",
  "React Three Fiber",
];
